---
- name: Install mysql to aws ec2 instance
  hosts: awsmysqlservers
  become: true
  gather_facts: False

  vars:
    database1_name: "petclinic"
    database2_name: "mydatabase2"
    mysql:
      hosts:
        - "{{ ansible_hostname }}"
        - 127.0.0.1
        - ::1
        - localhost
      binds:
        - 0.0.0.0

  roles:
    - mysql
