---
- name: Generate SSH keys
  hosts: 127.0.0.1
  connection: local

  vars:
    ssh_key_file: id_rsa_awsmymysql

  tasks:
    - name: Create directory if not exist
      ansible.builtin.file:
        path: "secrets/awsmysqlserver"
        state: directory
        mode: "0755"

    - name: Generate SSH key "{{ssh_key_file}}"
      openssh_keypair:
        path: "secrets/awsmysqlserver/{{ssh_key_file}}"
        type: rsa
        size: 4096
        state: present
        force: no
        comment: awsmymysql
