# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV["LC_ALL"] = "en_US.UTF-8"

Vagrant.configure("2") do |config|
  config.env.enable

  boxes = [
    {
      :name => ENV['MYSQLSERVER_NAME'] || "mysqlserver",
      :ip => ENV['MYSQLSERVER_IP'] || "192.168.1.70",
      :mem => ENV['MYSQLSERVER_MEMORY'] || "512",
      :cpu => ENV['MYSQLSERVER_CPU'] || "2"
    }
  ]

  config.vm.box = "ubuntu/focal64"
  #config.vm.synced_folder ".", "/vagrant", id: "vagrant-root", disabled: true
  boxes.each do |opts|
    config.vm.define opts[:name] do |config|
      config.vm.hostname = opts[:name]
      config.vm.provider "virtualbox" do |v|
        v.customize ["modifyvm", :id, "--name", opts[:name]]
        v.customize ["modifyvm", :id, "--memory", opts[:mem]]
        v.customize ["modifyvm", :id, "--cpus", opts[:cpu]]
      end
      config.vm.network :public_network, bridge: ENV['HOST_BRIDGE'], ip: opts[:ip], hostname: true
    end
  end
end
