---

- name: create a random password for users
  ansible.builtin.debug:
    msg: "{{ lookup('password', 'secrets/' + inventory_hostname + '/' + item.name + '/mysqlpassword  encrypt=sha512_crypt length=18 chars=ascii_letters') }}"
  loop: "{{ users }}"

- name: create a mysql user with a password
  ansible.builtin.command: 
    mysql -uroot -e "CREATE USER '{{ item.name }}'@'{{ item.host }}' IDENTIFIED BY '{{ lookup("password", "secrets/" + inventory_hostname + "/" + item.name + "/mysqlpassword") }}' ;"
  loop: "{{ users }}"

...