---
- name: Create users
  community.mysql.mysql_user:
    name: "{{ item.0.name }}"
    host: "{{ item.1 }}"
    priv: "{{ item.0.privs | join('/') }}"
    password: "{{ lookup('password', 'secrets/' + inventory_hostname + '/' + item.0.name + '/mysqlpassword length=18 chars=ascii_letters') }}"
  with_subelements:
    - "{{ users }}"
    - hosts
