---

# - name: Update apt-get repo and cache
#   apt: 
#     update_cache=yes
#     force_apt_get=yes
#     cache_valid_time=3600

# - name: Upgrade all apt packages
#   apt:
#     upgrade=dist
#     force_apt_get=yes

- name: Install htop
  ansible.builtin.apt:
    name: htop
    state: present

# - name: Install mysql-server
#   ansible.builtin.apt:
#     name: mysql-server
#     state: present
#     # update_cache: no

# - name: Enable a service mysql
#   ansible.builtin.systemd:
#     enabled: yes
#     name: mysql.service

# - name: Make sure a service mysql is started
#   ansible.builtin.systemd:
#     state: started
#     name: mysql.service

...