---
- name: Uninstall mysql
  import_tasks: "uninstall_mysql.yml"
  tags:
    - uninstall

- name: Add swap
  import_tasks: "add_swap.yml"
  tags:
    - swap
    - install

- name: Install mysql
  import_tasks: "install_mysql.yml"
  tags:
    - install

- name: Mysql secure installation
  import_tasks: "secure.yml"
  tags:
    - install
    - secure

- name: Create database
  import_tasks: "create_db.yml"
  tags:
    - install
    - database

- name: Create users
  import_tasks: "create_users.yml"
  tags:
    - install
    - users
