---
ecr_account_id: "{{ secret_ecr_account_id }}"
users:
  - name: joe
    hosts:
      - 91.193.131.121
    privs:
      - "{{ database1_name }}.*:ALL"
      - "{{ database2_name }}.*:SELECT"
      - "{{ database2_name }}.*:INSERT"
  - name: jim
    hosts:
      - "%"
    privs:
      - "{{ database1_name }}.*:ALL"
      - "{{ database2_name }}.*:ALL"
  - name: contabo
    hosts:
      - "{{ my_vps_ip }}" 
    privs:
      - "{{ database1_name }}.*:ALL"
      - "{{ database2_name }}.*:ALL"