---
all:
  hosts:
    myubuntu:
    mysqlserver:
    mysqlserver2:
    awsmysqlserver:
    bastion:
  children:
    mysqlservers:
      hosts:
        # myubuntu:
        mysqlserver:
        mysqlserver2:
    awsmysqlservers:
      hosts:
        awsmysqlserver:
    allmysqlservers:
      hosts:
        # myubuntu:
        mysqlserver:
        mysqlserver2:
        awsmysqlserver: